sudo: required
language: generic

env:
  global:
    - SFOS_VERSION=2.2.0.29
    - IMAGE=coderus/sailfishos-platform-sdk:${SFOS_VERSION}

services:
  - docker

matrix:
  include:
  - name: "armv7hl"
    env:
      - TARGET_PREFIX=sailfish_latest_
      - TARGET=armv7hl
      - ABI=gnueabi
  - name: "i486"
    env:
      - TARGET_PREFIX=sailfishos_latest_latest_
      - TARGET=i486
      - ABI=gnu

before_install:
  - ls
  - docker pull $IMAGE
  - docker run -it --mount type=bind,source="$(pwd)",target=/home/nemo/libipfs-git -d --name build-engine coderus/sailfishos-platform-sdk:$SFOS_VERSION /bin/bash
  - docker exec build-engine sb2 -t SailfishOS-$SFOS_VERSION-$TARGET -m sdk-install -R zypper --non-interactive --no-gpg-checks ar -f http://repo.merproject.org/obs/home:/skvark/${TARGET_PREFIX}${TARGET} go
  - docker exec build-engine sb2 -t SailfishOS-$SFOS_VERSION-$TARGET -m sdk-install -R zypper --non-interactive --no-gpg-checks ref
  - docker exec build-engine ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

script:
  - docker exec -e SFOS_VERSION=${SFOS_VERSION} -e TARGET=$TARGET -e ABI=$ABI build-engine bash -c "cd /home/nemo
    && cp -r libipfs-git libipfs
    && cd libipfs
    && sudo ln -s /srv/mer/toolings/SailfishOS-${SFOS_VERSION}/opt/cross/bin/${TARGET}-meego-linux-${ABI}-as /srv/mer/toolings/SailfishOS-${SFOS_VERSION}/opt/cross/libexec/gcc/${TARGET}-meego-linux-${ABI}/4.8.3/as
    && sudo ln -s /srv/mer/toolings/SailfishOS-${SFOS_VERSION}/opt/cross/bin/${TARGET}-meego-linux-${ABI}-ld /srv/mer/toolings/SailfishOS-${SFOS_VERSION}/opt/cross/libexec/gcc/${TARGET}-meego-linux-${ABI}/4.8.3/ld
    && mb2 -t SailfishOS-${SFOS_VERSION}-${TARGET} build
    && sudo cp RPMS/*.rpm /home/nemo/libipfs-git/"

deploy:
  provider: releases
  api_key:
    secure: OPfewpDqgMBcXpXWcQY7plkyhkpQiDSShEqX5Yny32EMB8u8a/LKn/X33TGJUKdYzXQH/bfAwDOhNO+yRXFAZkUIn45zU0LjOpbqxcBJH5ZyTHLerT3O6xUKFGR8od1VTT/XfRcD/jztbHePpXosvJGSMGbvDIVc4guq17GaqoHRIDTSU5RiyVD7bPO+fdkPBQtmpJYR7GCfsSISXnty40ou0pKzTJn2eiC3cZcNtgbFGihJ7M9aCgyL8ZBL55RudVyUf9HgjiPYteRuPtXP6uC2avwjAHwZ23xQFqmsWln6Q2MpFr3KMG5Ij6dojJmfP1gMIW2Uq1KasXdBFS6QDpklhoYwwhuX28GtWsxCCkNUTAkF3lQ+sdHdVude+wt6Stpa+TcXN/FHQ44lIEf92ED9G+vbjR+Yzk4ZcpTCLlYTC74ABSjWLUgnoVKWAlGM3OLNL8iXjJwy1ETEDpVIxMapfcETK2Mu+2I6JPGSW6+dUyyQk19TNkou5zFem84DcYN1iBLr8MiyJhmf5xY7rSHG0Fr4iF6s4O3DsztsWgdUHEqhgtf9q5YC/rFl3MuzGdRDz0IDQOTFF0Yqff8A8wpCOo/emhQDNSbzaRAhSm05gE9SCsefhdtaiWHzi2aX8x6i2iezoKOx7n/VMWw4lRvDQC75vyMj5iJ5aTWInB4=
  file_glob: true
  file: "*.rpm"
  skip_cleanup: true
  on:
    tags: true